---
- name: Setup local Ansible configuration
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "target_host"
      prompt: "Please provide the IP address of the target host"
      default: "localhost"
      private: no

  tasks:
  - name: Create ansible folders defined in ansible.cfg
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - ansible/inventory
    - ansible/cache
    - ansible/logs
    - ansible/roles
    - ansible/tmp
    - ansible/library

  - name: Generate configuration files
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      force: yes
    with_items:
    - { src: "resources/ansible-template.cfg.j2", dest: "./ansible.cfg" }
    - { src: "resources/inventory-template.j2", dest: "ansible/inventory/devportal" }

