---
- name: Keycloak Installer
  hosts: sso-test
  become: true
  vars:
    keycloak_ver: '4.1.0.Final'
    keycloak_mirror: https://downloads.jboss.org/keycloak
    keycloak_parent_install_dir: /usr/local
    keycloak_checksums:
      # https://downloads.jboss.org/keycloak/4.1.0.Final/keycloak-4.1.0.Final.tar.gz.sha1
      '4.1.0.Final': sha1:3be5b14bfd9a5cddd41b2ae06263b7b5273f1fc1
      # https://downloads.jboss.org/keycloak/3.2.1.Final/keycloak-3.2.1.Final.tar.gz.sha1
      '3.2.1.Final': sha1:de6d7ac62e2a82c7ecdfcf04c9970163415d9b75
      # https://downloads.jboss.org/keycloak/3.4.3.Final/keycloak-3.4.3.Final.tar.gz.sha1
      '3.4.3.Final': sha1:f2b1272ab8d4413f408b444bc2108740845bc976

  pre_tasks:
  - name: Update system packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
    - mod_ssl
    - openssl
    - libcurl
    - tree

  roles:
  - ansible-keycloak

  tasks:
  - name: Restarting node now
    shell: sleep 2 && reboot now
    async: 1
    poll: 0

  - name: Waiting for server to complete restarting
    local_action:
      module: wait_for
      host: '{{ inventory_hostname }}'
      state: started
      delay: "{{ start_check_delay | d(15) }}"
      timeout: '{{ server_restart_timeout | d(60) }}'

  - name: Start Keycloak server
    tags: ['start']
    become: true
    shell: /usr/local/keycloak/bin/standalone.sh
    async: 45
    poll: 0



