---
- name: Update openldap node
  hosts: ldap
  gather_facts: no
  tags: ['os-pre-req']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-os-openldap, tags: ['openldap'] }
