---
- name: Configure Postgres Master
  hosts: "{{ pg_master_node }}"
  gather_facts: no
  serial: 1
  tags: ['pg', 'pgmaster']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-postgres-config, tags: ['pg-os-pre-req'] }
  - { role: apigee-opdk-setup-postgres-master }
  - { role: apigee-opdk-setup-status, tags: ['status'] }

- name: Configure Postgres Standby
  hosts: "{{ pg_standby_node }}"
  gather_facts: no
  serial: 1
  tags: ['pg', 'pgstandby']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-stop-components, component_name: 'apigee-postgresql' }
  - { role: apigee-opdk-setup-postgres-config, tags: ['pg-os-pre-req'], clear_pgdata: True }
  - { role: apigee-opdk-setup-postgres-standby }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
