---
- name: Configure influxdb
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['influxdb']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component-install, component: 'apigee-influxdb', tags: ['influxdb'] }
  - { role: apigee-opdk-setup-component-setup, component: 'apigee-influxdb', tags: ['influxdb'] }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
