---
- name: Update planet cache
  tags: ['cache']
  import_playbook: apigee-planet-cache.yml
  vars:
    target_hosts: ms,pg,sso

- name: Install and configure Openldap pre-requisites
  import_playbook: apigee-os-pre-requisites-epel.yml
  tags: ['os', 'os-epel']
  vars:
    target_hosts: sso

- name: Install and configure OS pre-requisites
  import_playbook: apigee-os-pre-requisites.yml
  tags: ['os']
  vars:
    target_hosts: sso

- name: Install and configure Pip pre-requisites
  import_playbook: apigee-os-pre-requisites-pip.yml
  tags: ['os', 'os-pip']
  vars:
    target_hosts: sso

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-bootstrap.yml
  tags: ['bootstrap']
  vars:
    target_hosts: sso

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-common-install.yml
  tags: ['common']
  vars:
    target_hosts: sso

- name: Configure Apigee pre-requisites
  import_playbook: apigee-edge-configuration.yml
  tags: ['pg','pg-config','config']
  vars:
    target_hosts: sso-pg

- name: Install Postgres node
  import_playbook: install-edge-pg-component-setup.yml
  tags: ['pg','pg-setup']
  vars:
    target_hosts: sso-pg

- name: Install Edge SSO
  hosts: sso
  gather_facts: no
  tags: ['sso']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component-install, component: 'apigee-ssoadminapi' }
  - { role: apigee-opdk-setup-edge-sso-config, tags: ['sso-config'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user'] }
  - { role: apigee-opdk-setup-component, profile: 'sso', target_response_file_path: "{{ edge_sso_installation_config_file_path }}", tags: ['sso-setup']  }
  - { role: apigee-opdk-setup-edge-saml-config, tags: ['saml-config'] }

