---
- name: Configure Cassandra & Zookeeper in dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  serial: 1
  tags: ['baas-cs']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component, profile: '{{ component_profile }}', target_response_file_path: '{{ opdk_baas_silent_install_file_path }}' }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
