---
- name: Configure DevPortal UI
  hosts: "{{ target_hosts }}"
  become: yes
  serial: 1
  gather_facts: no
  tags: ['dp']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-devportal-config, tags: ['config'] }
  - { role: apigee-opdk-setup-component, profile: 'dp',tags: ['apigee-component'], target_response_file_path: "{{ opdk_portal_config_file }}" }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
