---
- name: Setup Qpid on dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['qpid']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml

#  roles:
#  - { role: apigee-opdk-setup-component, profile: 'qs', tags: ['apigee-component'] }
#  - { role: apigee-opdk-update-component-qpidd, tags: ['apigee-component-update'] }
#  - { role: apigee-opdk-start-components, server_types: ['qs'], tags: ['self'] }

  tasks:
  - block:

    - name: Install Apigee Qpid Component
      tags: ['apigee-component']
      import_role:
        name: apigee-opdk-setup-component
      vars:
        profile: 'qs'

    rescue:
      - name: Ensure that yum support is installed
        yum:
          name: "{{ item }}"
          state: present
        with_items:
        - yum-utils
        - yum-plugin-priorities

      - name: Use Apigee Qpid Work Around
        become: true
        shell: yum --setopt=obsoletes=0 install apigee-qpidd -y

      - name: Install Apigee Qpid Component
        tags: ['apigee-component']
        import_role:
          name: apigee-opdk-setup-component
        vars:
          profile: 'qs'

  - name: Start Apigee Qpid Component
    tags: ['self']
    import_role:
      name: apigee-opdk-start-components
    vars:
      server_types: ['qs']

  - name: Collect Self Report for Apigee Qpid
    tags: ['self']
    import_role:
      name: apigee-opdk-server-self
    vars:
      server_types: ['qs']

  - name: Assert Setup Status
    tags: ['status']
    import_role:
      name: apigee-opdk-setup-status
