---
- name: Update planet cache
  import_playbook: apigee-planet-cache.yml
  tags: ['cache']
  vars:
    target_hosts: mirror,ms

- name: Install and configure OS pre-requisites
  import_playbook: apigee-os-pre-requisites.yml
  tags: ['os']
  vars:
    target_hosts: mirror

- name: Install and configure Openldap pre-requisites
  import_playbook: apigee-os-pre-requisites-epel.yml
  tags: ['os', 'os-epel']
  vars:
    target_hosts: mirror

- name: Install and configure Pip pre-requisites
  import_playbook: apigee-os-pre-requisites-pip.yml
  tags: ['os', 'os-pip']
  vars:
    target_hosts: mirror

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-bootstrap.yml
  tags: ['bootstrap']
  vars:
    target_hosts: mirror

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-common-install.yml
  tags: ['common']
  vars:
    target_hosts: mirror

- name: Create apigee mirror archive
  hosts: mirror
  gather_facts: no
  tags: ['create']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-create-archive, tags: ['create-archive'] }

- name: Download apigee mirror archive
  hosts: mirror
  gather_facts: no
  tags: ['download']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-download-archive, tags: ['download-archive'] }

- name: Upload apigee mirror archive
  hosts: cf-000,cf-001,cf-002,cf-003,cf-004
#  hosts: mirror
  gather_facts: no
  tags: ['upload']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-upload-archive, tags: ['upload-archive'] }

- name: Install apigee mirror archive
  hosts: cf-000,cf-001,cf-002,cf-003,cf-004
#  hosts: mirror
  gather_facts: no
  tags: ['install']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-bootstrap-archive-installer, tags: ['install-archive'] }

- name: Expose apigee mirror web server
  hosts: mirror
  gather_facts: no
  tags: ['nginx']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-mirror-nginx, tags: ['nginx-mirror'] }

- name: Download logs and configs
  tags: ['logs']
  import_playbook: apigee-log-config-files.yml
  vars:
    target_hosts: mirror
