---
- name: Setup Monetization on dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['mint-cluster']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-mint-mgmt-cluster }
