---
- name: Setup Monetization on dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['mo']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-provisioning, provisioning_action: 'enable-monetization', provisioning_config_file: '{{ target_response_file_path }}'}
