---
- name: Test Apigee OPDK OS Pre-Requisites Role
  hosts: planet
  gather_facts: yes
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - apigee-opdk-os-pre-requisites


