---
- name: Test Apigee OPDK OS Pre-Requisites Role
  hosts: planet
  gather_facts: yes
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }
  - { role: apigee-opdk-os-pre-requisites, tags: ['os'] }
  - { role: apigee-opdk-setup-os-openldap, tags: ['openldap'] }
  - { role: apigee-opdk-pre-requisites, tags: ['bootstrap'] }
  - { role: apigee-opdk-setup-silent-installation-config, tags: ['config']}



