---
- name: Test Apigee OPDK OS Pre-Requisites Role
  hosts: aio
  gather_facts: yes
  become: true
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }
  - { role: apigee-opdk-os-pre-requisites, tags: ['os'] }
  - { role: apigee-opdk-setup-os-openldap, tags: ['openldap'] }
  - { role: apigee-opdk-pre-requisites, tags: ['bootstrap'] }
  - { role: apigee-opdk-setup-silent-installation-config, tags: ['config']}
  - { role: apigee-opdk-setup-os-postgres, tags: ['pg-os-pre-req'] }
  - { role: apigee-opdk-setup-component, profile: 'aio' }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
  - { role: apigee-opdk-setup-org-config, tags: ['org-config'] }
  - { role: apigee-opdk-setup-org, tags: ['org-create'] }
  - { role: apigee-opdk-setup-validate, tags: ['validate'] }
  - { role: apigee-opdk-setup-validate-cleanup, tags: ['validate', 'validate-cleanup'] }
  - { role: apigee-fetch-files, download_pattern: '{{ pattern }}', download_folder: "{{ target_logs_folder }}", tags: ['logs'] }
