---
- name: Upgrade PS component
  hosts: pgmaster
  become: yes
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['pgmaster-update', 'pgmaster']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component ps on {{ inventory_hostname }} ( {{ ansible_hostname }} )"

  roles:
  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self']  }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['ps'] }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-stop-components, component_name: "edge-postgres-server", when: "opdk_version is version_compare('4.18.01', '==')" }
  - { role: apigee-opdk-stop-components, component_name: "apigee-postgresql", when: "opdk_version is version_compare('4.18.01', '==')" }
  - { role: apigee-opdk-update-component,  component: 'ps', validate_ready: false, ignore_errors: true, tags: ['pgmaster-ps-update']}
  - { role: apigee-opdk-setup-postgres-db-upgrade, tags: ['pgmaster-db-upgrade'], when: "opdk_version is version_compare('4.18.01', '==')" }
  - { role: apigee-opdk-update-component,  component: 'edge', validate_ready: false, ignore_errors: true, tags: ['pgmaster-edge-update'] }
  - { role: apigee-opdk-start-components, component_name: "edge-postgres-server", when: "opdk_version is version_compare('4.18.01', '==')" }
  - { role: apigee-opdk-start-components, component_name: "apigee-postgresql", when: "opdk_version is version_compare('4.18.01', '==')" }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['ps'] }
#  tasks:
#  - name: Validate Postgresql master
#    shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-postgresql postgres-check-master"

- name: Upgrade Postgres standby
  hosts: pgstandby
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['pgstandby-update', 'pgstandby']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component ps on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self']  }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-stop-components, component_name: "edge-postgres-server", when: "opdk_version is version_compare('4.18.01', '==')" }
  - { role: apigee-opdk-stop-components, component_name: "apigee-postgresql", when: "opdk_version is version_compare('4.18.01', '==')" }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'], clear_pgdata: True }
  - { role: apigee-opdk-update-component,  component: 'ps', validate_ready: false, ignore_errors: true, tags: ['pgstandby-upgrade'] }
  - { role: apigee-opdk-update-component,  component: 'edge', validate_ready: false, ignore_errors: true, tags: ['pgstandby-edge-upgrade'] }
  - { role: apigee-opdk-setup-postgres-standby }
  - { role: apigee-opdk-cwc-update, when: update_max_wal_settings is defined and update_max_wal_settings }
  - { role: apigee-opdk-stop-components, tags: ['stop'], when: update_max_wal_settings is defined and update_max_wal_settings  }
  - { role: apigee-opdk-start-components, tags: ['start'],  when: update_max_wal_settings is defined and update_max_wal_settings }
  - { role: apigee-opdk-setup-postgres-standby, when: update_max_wal_settings is defined and update_max_wal_settings }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['ps'] }
