---
galaxy_info:
  author: Andrew Rothstein
  description: Installs keycloak
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - sso
    - key-management

dependencies: []

  
