---
- name: Remove servers
  hosts: ms[0]
  gather_facts: no
  vars:
    org: VALIDATE
    env: dev
    pod: gateway
    property_folders:
    - "~/.apigee-secure"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-settings-region }
  - { role: apigee-opdk-settings-private-address }
  - { role: apigee-opdk-settings-management-server }

  tasks:
  - name: Obtain list of environments for organizations
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e/{{ env }}/"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
    register: env_list

  - name: Obtain list of servers for environment
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e/{{ env }}/{{ item }}"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
    with_items: "{{ env_list.json }}"
    register: server_uuids

  - name: Delete servers from environment
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/organizations/{{ org }}/environments/{{ list.json.name }}/servers"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
      method: POST
      body_format: form-urlencoded
      body:
        action: remove
        uuid: "{{ item }}"
        region: "{{ region }}"
        pod: "{{ pod }}"
    with_items: "{{ server_uuids }}"
