---
- name: Install AIO
  hosts: edge

  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }
  - { role: apigee-opdk-os-pre-requisites, tags: ['cache'] }
  - { role: apigee-opdk-setup-target-links, tags: ['links', 'bootstrap'] }
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-java-home, tags: ['java-home', 'bootstrap'] }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap', 'bootstrap'] }
  - { role: apigee-opdk-setup-license, tags: ['license', 'bootstrap'] }
  - { role: apigee-opdk-setup-component-install, component: 'apigee-setup', tags: ['setup', 'apigee-component-install', 'apigee-pre-req','common-install', 'common'] }
  - { role: apigee-opdk-setup-component-install, component: 'apigee-adminapi', tags: ['adminapi', 'apigee-component-install', 'apigee-pre-req','common-install', 'common'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user','ownership', 'apigee-pre-req','common-install', 'common'] }
  - { role: apigee-opdk-modules, tags: ['apigee-config'] }
  - { role: apigee-opdk-setup-silent-installation-config, tags: ['apigee-config'] }
  - { role: apigee-opdk-setup-component, profile: 'aio', tags: ['aio'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
  - { role: apigee-opdk-setup-org-config, tags: ['org-config'] }
  - { role: apigee-opdk-setup-org, tags: ['org-create'] }
  - { role: apigee-opdk-setup-validate, tags: ['validate'] }
  - { role: apigee-opdk-setup-validate-cleanup, tags: ['validate', 'validate-rmp-cleanup'] }
  - { role: apigee-fetch-files, download_pattern: '{{ pattern }}', download_folder: "{{ target_logs_folder }}" }

 vars:
    pattern:
    - { dir: '/etc/', pattern: 'hosts*' }
    - { dir: '/etc/', pattern: 'environment' }
    - { dir: '/etc/', pattern: 'profile' }
    - { dir: '/etc/', pattern: 'bashrc' }
    - { dir: '/etc/', pattern: 'resolv.conf' }
    - { dir: '/etc/', pattern: 'sysctl.conf' }
    - { dir: '/etc/', pattern: 'sudoers' }
    - { dir: '/etc/security/', pattern: 'limits.conf' }
    - { dir: '/etc/security/limits.d/', pattern: '*conf' }
    - { dir: '/var/log/', pattern: 'messages' }
    - { dir: '/tmp', pattern: 'setup*.log' }
    - { dir: '{{ opdk_installer_path }}/', pattern: '*' }
    - { dir: '{{ apigee_home }}/', pattern: '*.out' }
    - { dir: '{{ apigee_home }}/var/log', pattern: '*.log' }
    - { dir: '{{ apigee_home }}/customer/', pattern: '*' }
    - { dir: '{{ apigee_home }}/etc/', pattern: 'default*.sh' }
    - { dir: '{{ apigee_home }}/customer', pattern: '*' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*conf' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*cfg' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*yml' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*yaml' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*properties' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*conf' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*cfg' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*yml' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*yaml' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*properties' }
    - { dir: '{{ apigee_home }}/apigee-postgresql/', pattern: '*conf' }



#- name: Update planet cache
#  tags: ['cache']
#  import_playbook: apigee-planet-cache.yml
#  vars:
#    target_hosts: edge
#
#- name: Install and configure OS pre-requisites
#  import_playbook: apigee-os-pre-requisites.yml
#  tags: ['os']
#  vars:
#    target_hosts: edge
#
#- name: Install and configure Openldap pre-requisites
#  import_playbook: apigee-os-pre-requisites-epel.yml
#  tags: ['os', 'os-epel']
#  vars:
#    target_hosts: edge
#
#- name: Install and configure Openldap pre-requisites
#  import_playbook: apigee-os-pre-requisites-openldap.yml
#  tags: ['os', 'os-openldap']
#  vars:
#    target_hosts: ms
#
#- name: Install and configure Pip pre-requisites
#  import_playbook: apigee-os-pre-requisites-pip.yml
#  tags: ['os', 'os-pip']
#  vars:
#    target_hosts: edge
#
#- name: Install and configure Postgres pre-requisites
#  import_playbook: apigee-os-pre-requisites-postgres.yml
#  tags: ['os', 'os-postgres']
#  vars:
#    target_hosts: pg

#- name: Install Apigee pre-requisites
#  import_playbook: apigee-pre-requisites-bootstrap.yml
#  tags: ['bootstrap']
#  vars:
#    target_hosts: edge
#
#- name: Install Apigee pre-requisites
#  import_playbook: apigee-pre-requisites-common-install.yml
#  tags: ['common']
#  vars:
#    target_hosts: edge

#- name: Configure installation file
#  import_playbook: apigee-edge-configuration.yml
#  tags: ['config']
#  vars:
#    target_hosts: edge

#- name: Install and configure Apigee Edge AIO
#  hosts: edge
#  gather_facts: no
#  tags: ['aio']
#  serial: 1
#  vars:
#    yum_manual_os_packages:
#    - openldap-servers
#  roles:
#  - { role: apigee-opdk-setup-component, profile: 'aio' }
#
#- name: Setup org
#  include: install-edge-setup-org.yml
#  tags: ['org']
#  vars:
#    target_hosts: ms[0]
#
#- name: Validate RMP
#  include: install-edge-rmp-validate.yml
#  tags: ['validate-rmp']
#  vars:
#    target_hosts: rmp

#- name: Download logs and configs
#  tags: ['logs']
#  include: apigee-log-config-files.yml
#  vars:
#    target_hosts: edge


