---
- hosts: ms
  vars:
    cwc_properties:
    - { key: 'conf_security_externalized.authentication.implementation.class', value: 'com.apigee.sampleCustomer.impl.LdapAuthenticatorImpl', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.bind.direct.type', value: 'false', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.server.url', value: 'ldap://secure.ldap.customer.com:389', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.server.version', value: '3', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.server.conn.timeout', value: '50000', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.user.store.baseDN', value: 'dc=ldap,dc=customer,dc=com', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.user.store.search.query', value: '(&(${userAttribute}=${userId}))', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.user.store.user.attribute', value: 'mail', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.indirect.bind.server.admin.dn', value: 'cn=s.bind.npad.apigee,ou=Special.Accounts,dc=ldap,dc=customer,dc=com', file_name: 'edge-management-server' }
    - { key: 'conf_security_externalized.authentication.indirect.bind.server.admin.dn', value: 'cn=s.bind.npad.apigee,ou=Special.Accounts,dc=ldap,dc=customer,dc=com', file_name: 'edge-management-server' }
  roles:
  - apigee-opdk-cwc-update

