---
- name: Setup local Ansible configuration
  hosts: localhost
  gather_facts: no

  vars:
    opdk_user_name: 'apigee'
    opdk_group_name: 'apigee'

  vars_prompt:
    - name: "target_host"
      prompt: "Please provide the IP address of the target host"
      default: "localhost"

  tasks:
  - name: Generate ansible.cfg file
    template:
      src: resources/ansible-template.cfg.j2
      dest: "{{ playbook_dir }}/ansible.cfg"

  - name: Create ansible folders defined in ansible.cfg
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - ansible/inventory
    - ansible/cache
    - ansible/logs
    - ansible/roles
    - ansible/tmp
    - ansible/library

  - name: Generate inventory file
    template:
      dest: ansible/inventory/aio
      src: resources/aio-template.j2
