---
- name: Setup local Ansible configuration
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Generate ansible.cfg file
    template:
      src: resources/ansible-template.cfg.j2
      dest: "{{ playbook_dir }}/ansible.cfg"