---
- name: Gathering Setup for Planet
  hosts: planet

  tasks:
  - name: Gather setup
    setup:


- name: Install Edge Mirror
  hosts: "{{ target_hosts }}"
  tags: ['install']
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/apigee-workspace"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }
#  - { role: apigee-opdk-os-pre-requisites, tags: ['os'] }
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-os-epel, tags: ['epel'] }
  - { role: apigee-opdk-shutdown-iptables, tags: ['iptables'] }
  - { role: apigee-opdk-yum-repository-proxy-config, tags: ['yum-proxy-config']}
  - { role: apigee-opdk-setup-os-minimum, tags: ['os-minimum'] }
#  - { role: apigee-opdk-setup-os-limits, tags: ['limit'] }
  - { role: apigee-opdk-setup-os-sysctl, tags: ['sysctl'] }
  - { role: apigee-opdk-setup-selinux-disable, tags: ['selinux'] }
  - { role: apigee-server-restart, tags: ['restart-server'], start_check_delay: 30, when: (selinux_disabled is defined and selinux_disabled.changed) or (iptables_disabled is defined and not iptables_disabled) or (force_restart is defined and force_restart)  }
  - { role: apigee-opdk-setup-os-common, tags: ['os-common'] }
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-java-home, tags: ['java-home', 'bootstrap'] }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap', 'bootstrap'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-bootstrap-create-archive, tags: ['bootstrap', 'create'] }

- name: Download log files
  hosts: edge
  gather_facts: no
  become: true
  tags: ['logs']
  roles:
  - { role: apigee-fetch-files, download_pattern: '{{ pattern }}', download_folder: "{{ playbook_dir }}/{{ target_logs_folder }}" }
  vars:
    opdk_installer_path: /tmp/edge
    apigee_home: /opt/apigee
    target_logs_folder: planet_logs
    pattern:
    - { dir: '/etc/', pattern: 'hosts*' }
    - { dir: '/etc/', pattern: 'environment' }
    - { dir: '/etc/', pattern: 'profile' }
    - { dir: '/etc/', pattern: 'bashrc' }
    - { dir: '/etc/', pattern: 'resolv.conf' }
    - { dir: '/etc/', pattern: 'sysctl.conf' }
    - { dir: '/etc/', pattern: 'sudoers' }
    - { dir: '/etc/security/', pattern: 'limits.conf' }
    - { dir: '/etc/security/limits.d/', pattern: '*conf' }
    - { dir: '/var/log/', pattern: 'messages' }
    - { dir: '/tmp', pattern: 'setup*.log' }
    - { dir: '{{ opdk_installer_path }}/', pattern: '*' }
    - { dir: '{{ apigee_home }}/', pattern: '*.out' }
    - { dir: '{{ apigee_home }}/var/log', pattern: '*.log' }
    - { dir: '{{ apigee_home }}/customer/', pattern: '*' }
    - { dir: '{{ apigee_home }}/etc/', pattern: 'default*.sh' }
    - { dir: '{{ apigee_home }}/customer', pattern: '*' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*conf' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*cfg' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*yml' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*yaml' }
    - { dir: '{{ apigee_home }}/apigee-cassandra/', pattern: '*properties' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*conf' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*cfg' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*yml' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*yaml' }
    - { dir: '{{ apigee_home }}/apigee-zookeeper/', pattern: '*properties' }
    - { dir: '{{ apigee_home }}/apigee-postgresql/', pattern: '*conf' }

