---
- name: Download apigee mirror archive
  hosts: mirror
  gather_facts: no
  tags: ['download']
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/apigee-workspace"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-setup-bootstrap-download-archive, tags: ['download-archive'] }
