---
- name: Install apigee mirror archive
  hosts: "{{ target_hosts }}"
  tags: ['install']
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/apigee-workspace"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:

  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }
#  - { role: apigee-opdk-os-pre-requisites, tags: ['os'] }
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-bootstrap-archive-installer, tags: ['install-archive'] }

