---
- name: Install apigee mirror archive
  hosts: "{{ target_hosts }}"
  tags: ['install']
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/apigee-workspace"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-setup-bootstrap-archive-installer, tags: ['install-archive'] }

