---
- name: Upload apigee mirror archive
  hosts: "{{ target_hosts }}"
  tags: ['upload']
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/apigee-workspace"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-setup-bootstrap-upload-archive, tags: ['upload-archive'] }
