---
- name: Router Registration Status
  hosts: rmp
  gather_facts: no
  tags: ['router']
  roles:
    - { role: apigee-opdk-server-self, server_types: ['router'], tags: ['self'] }
    - { role: apigee-opdk-server-registration-state, username: "{{ opdk_user_email }}", password: "{{ opdk_user_pass }}", server_self: "{{ edge_router_self }}", mgmt_server_ip: "{{ local_mgmt_ip }}" }

- name: Message Processor Registration Status
  hosts: rmp
  gather_facts: no
  tags: ['mp']
  roles:
    - { role: apigee-opdk-server-self, server_types: ['mp'], tags: ['self'] }
    - { role: apigee-opdk-server-registration-state, username: "{{ opdk_user_email }}", password: "{{ opdk_user_pass }}", server_self: "{{ edge_mp_self }}", mgmt_server_ip: "{{ local_mgmt_ip }}" }


