---
- name: Playbook to remove zookeeper
  hosts: "{{ target_hosts }}"
  gather_facts: no

  vars:
    property_folders:
    - '~/.apigee'
    - '~/.apigee-secure'
    component_name: "apigee-zookeeper"

  tasks:

  - name: Remove Zookeeper
    include_tasks: remove-component.yml

#  - name: Backup zookeeper
#    tags: ['backup']
#    import_role:
#      name: apigee-opdk-backup
#    vars:
#      component_name: "apigee-zookeeper"
#
#  - name: Stop zookeeper
#    import_role:
#      name: apigee-opdk-stop-components
#    vars:
#      component_name: "apigee-zookeeper"
#
#  - name: Apigee-zookeeper uninstall
#    tags: ['uninstall']
#    ignore_errors: yes
#    shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-zookeeper uninstall"
#    when: apigee_service is defined and apigee_service | trim | length > 0
#
#  - name: Remove files
#    tags: ['remove']
#    become: yes
#    file:
#      path: '{{ apigee_home }}/data/apigee-zookeeper'
#      state: absent
#      follow: yes
#
#  - name: Remove node from inventory message
#    pause:
#       prompt: "Please remove this node from the inventory file and re-run setup"


