---
- name: Playbook to remove a cassandra
  hosts: "{{ target_hosts }}"
  gather_facts: no

  vars:
    nodetool: /opt/apigee/apigee-cassandra/bin/nodetool
    property_folders:
    - '~/.apigee'
    - '~/.apigee-secure'
    component_name: "apigee-cassandra"

  tasks:
  - name: Assert variables exist
    assert:
      that:
      - private_address is defined and private_address | trim | length > 0
      - nodetool is defined and nodetool | trim | length > 0
      msg: "Please provide the missing attribute"

  - block:
    - name: Decommission cassandra node
      command: "{{ nodetool }} decommission"

    rescue:
      - name: Remove node that is not a part of the ring
        command: "{{ nodetool }} removenode"

  - name: Remove Cassandra
    include_tasks: remove-component.yml
