---
- name: Playbook to remove zookeeper
  hosts: "{{ target_hosts }}"
  gather_facts: no

  vars:
    property_folders:
    - '~/.apigee'
    - '~/.apigee-secure'
    component_name: "apigee-zookeeper"

  tasks:

  - name: Remove Zookeeper
    include_tasks: remove-component.yml
