---
- name: Playbook to remove a cassandra
  hosts: "{{ target_hosts }}"
  gather_facts: no

  vars:
    nodetool: /opt/apigee/apigee-cassandra/bin/nodetool
    property_folders:
    - '~/.apigee'
    - '~/.apigee-secure'

  tasks:
  - name: Assert variables exist
    assert:
      that:
      - private_address is defined and private_address | trim | length > 0
      - nodetool is defined and nodetool | trim | length > 0
      msg: "Please provide the missing attribute"

  - name: Start Cassandra
    import_role:
      name: apigee-opdk-start-components
    vars:
      component_name: "apigee-cassandra"

#  - name: Backup Cassandra
#    import_role:
#      name: apigee-opdk-backup
#    vars:
#      component_name: "apigee-cassandra"

  - block:
    - name: Decommission cassandra node
      command: "{{ nodetool }} decommission"

    rescue:
      - name: Remove node that is not a part of the ring
        command: "{{ nodetool }} removenode"

  - name: Stop Cassandra
    import_role:
      name: apigee-opdk-stop-components
    vars:
      component_name: "apigee-cassandra"

  - name: Apigee uninstall
    ignore_errors: yes
    shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-service apigee-cassandra uninstall"
    when: apigee_service is defined and apigee_service | trim | length > 0

  - name: Remove files
    become: yes
    file:
      path: '{{ apigee_home }}/data/apigee-cassandra'
      state: absent
      follow: yes

  - name: Remove node from inventory
    pause:
       prompt: "Please remove this node from the inventory file and re-run setup"


