---
- name: Playbook to remove a cassandra
  hosts: "{{ target_hosts }}"
  gather_facts: no

  vars:
    nodetool: /opt/apigee/apigee-cassandra/bin/nodetool
    property_folders:
    - '~/.apigee'
    - '~/.apigee-secure'
    component_name: "apigee-router"
    server_type: 'r'

  roles:
  - { role: apigee-opdk-server-self, server_types: ['r'] }

  tasks:
  - name: Set attributes if available
    ignore_errors: true
    set_fact:
      uuid: "{{ edge_r_self.uUID }}"
      server_type: "{{ edge_r_self.type[0] }}"

  - name: Assert variables exist
    assert:
      that:
      - region is defined and region | trim | length > 0
      - pod is defined and pod_name | trim | length > 0
      - uuid is defined and uuid | trim | length > 0
      msg: "Please provide the missing attribute"

  - name: Remove Router
    include_tasks: remove-component.yml
