---
- name: Show Postgres Master Check
  hosts: pgmaster
  gather_facts: no
  tags: ['replication']
  vars:
    apigee_secure_folder: "~/.apigee-secure"
  vars_files:
  - "{{ apigee_secure_folder }}/credentials.yml"
  tasks:
  - name: Display Postgres Master Status Check
    shell: "{{ apigee_service }} apigee-postgresql postgres-check-master"

- name: Show Postgres Standby Check
  hosts: pgstandby
  gather_facts: no
  tags: ['replication']
  vars:
    apigee_secure_folder: "~/.apigee-secure"
  vars_files:
  - "{{ apigee_secure_folder }}/credentials.yml"
  tasks:
  - name: Display Postgres Standby Status Check
    shell: "{{ apigee_service }} apigee-postgresql postgres-check-standby"

- name: Postgres server self report
  hosts: pg
  gather_facts: no
  tags: ['ps-self', 'self']
  serial: 1
  vars:
    apigee_secure_folder: "~/.apigee-secure"
  vars_files:
  - "{{ apigee_secure_folder }}/credentials.yml"
  roles:
  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self'] }

- name: Postgres Registration Status
  hosts: pg
  gather_facts: no
  tags: ['pg-registration']
  vars:
    apigee_secure_folder: "~/.apigee-secure"
  vars_files:
  - "{{ apigee_secure_folder }}/credentials.yml"
  roles:
    - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self'] }
    - { role: apigee-opdk-server-registration-state, username: "{{ opdk_user_email }}", password: "{{ opdk_user_pass }}", server_self: "{{ edge_ps_self }}", mgmt_server_ip: "{{ local_mgmt_ip }}" }

- name: Analytics group scope state
  hosts: ms
  gather_facts: no
  tags: ['scope']
  vars:
    apigee_secure_folder: "~/.apigee-secure"
  vars_files:
  - "{{ apigee_secure_folder }}/credentials.yml"
  roles:
  - { role: apigee-opdk-setup-scopes-state,
      ax_group: "{{ scopes_axgroup | default('axgroup001') }}"
    }

- name: Analytics status
  hosts: ms[0]
  gather_facts: no
  tags: ['axstatus']
  vars:
    apigee_secure_folder: "~/.apigee-secure"
  vars_files:
  - "{{ apigee_secure_folder }}/credentials.yml"
  tasks:
  - name: List users
    uri:
      url: "http://127.0.0.1:8080/v1/organizations/{{ org_name }}/environments/{{ env_name }}/provisioning/axstatus"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"

- name: Analytics groups
  hosts: ms[0]
  gather_facts: no
  tags: ['axgroups']
  vars:
    apigee_secure_folder: "~/.apigee-secure"
  vars_files:
  - "{{ apigee_secure_folder }}/credentials.yml"
  tasks:
  - name: List users
    uri:
      url: "http://127.0.0.1:8080/v1/analytics/groups/ax"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"

- name: Describe analytics table
  hosts: pgmaster
  gather_facts: no
  tags: ['axtables']
  vars:
    apigee_secure_folder: "~/.apigee-secure"
  vars_files:
  - "{{ apigee_secure_folder }}/credentials.yml"
  tasks:
  - name: Describe postgres analytics table
    shell: "{{ psql }} -h {{ apigee_home }}/var/run/apigee-postgresql -w {{ pg_pass }} -c \"\\d analytics.'{{ org_name }}.{{ env_name }}.fact'\" -U {{ pg_user }} apigee"
